name: limesurvey-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - notebook
  - ipykernel
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  - scikit-learn
  - openpyxl
  - pyarrow
  - missingno
  - pip:
      - pingouin
      - researchpy
